// SPDX-FileCopyrightText: 2022 E F R <602406+Efruit@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Flipp Syder <76629141+vulppine@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Vera Aguilera Puerto <6766154+Zumorica@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 metalgearsloth <comedian_vs_clown@hotmail.com>
// SPDX-FileCopyrightText: 2022 mirrorcult <lunarautomaton6@gmail.com>
// SPDX-FileCopyrightText: 2022 vulppine <vulppine@gmail.com>
// SPDX-FileCopyrightText: 2023 Ilya246 <57039557+Ilya246@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 Visne <39844191+Visne@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 MilenVolf <63782763+MilenVolf@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Southbridge <7013162+southbridge-fur@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared.Atmos.Monitor.Components;
using Content.Shared.Atmos.Piping.Unary.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Atmos.Monitor.UI.Widgets;

[GenerateTypedNameReferences]
public sealed partial class PumpControl : BoxContainer
{
    private GasVentPumpDataPayload _dataPayload;
    private string _address;

    public event Action<string, AtmosDeviceDataPayload>? PumpDataChanged;
	public event Action<AtmosDeviceDataPayload>? PumpDataCopied;

    private CheckBox _enabled => CEnableDevice;
    private CollapsibleHeading _addressLabel => CAddress;
    private OptionButton _pumpDirection => CPumpDirection;
    private OptionButton _pressureCheck => CPressureCheck;
    private FloatSpinBox _externalBound => CExternalBound;
    private FloatSpinBox _internalBound => CInternalBound;
    private Button _copySettings => CCopySettings;

    public PumpControl(GasVentPumpDataPayload dataPayload, string address)
    {
        RobustXamlLoader.Load(this);

        Name = address;

        _dataPayload = dataPayload;
        _address = address;

        _addressLabel.Title = Loc.GetString("air-alarm-ui-atmos-net-device-label", ("address", $"{address}"));

        _enabled.Pressed = dataPayload.Enabled;
        _enabled.OnToggled += _ =>
        {
            _dataPayload.Enabled = _enabled.Pressed;
            PumpDataChanged?.Invoke(_address, _dataPayload);
        };

        _internalBound.Value = _dataPayload.InternalPressureBound;
        _internalBound.OnValueChanged += _ =>
        {
            _dataPayload.InternalPressureBound = _internalBound.Value;
            PumpDataChanged?.Invoke(_address, _dataPayload);
        };
        _internalBound.IsValid += value => value >= 0;

        _externalBound.Value = _dataPayload.ExternalPressureBound;
        _externalBound.OnValueChanged += _ =>
        {
            _dataPayload.ExternalPressureBound = _externalBound.Value;
            PumpDataChanged?.Invoke(_address, _dataPayload);
        };
        _externalBound.IsValid += value => value >= 0;

        foreach (var value in Enum.GetValues<VentPumpDirection>())
        {
            _pumpDirection.AddItem(Loc.GetString($"air-alarm-ui-pump-direction-{value.ToString().ToLower()}"), (int) value);
        }

        _pumpDirection.SelectId((int) _dataPayload.PumpDirection);
        _pumpDirection.OnItemSelected += args =>
        {
            _pumpDirection.SelectId(args.Id);
            _dataPayload.PumpDirection = (VentPumpDirection) args.Id;
            PumpDataChanged?.Invoke(_address, _dataPayload);
        };

        foreach (var value in Enum.GetValues<VentPressureBound>())
        {
            _pressureCheck.AddItem(Loc.GetString($"air-alarm-ui-pressure-bound-{value.ToString().ToLower()}"), (int) value);
        }

        _pressureCheck.SelectId((int) _dataPayload.PressureChecks);
        _pressureCheck.OnItemSelected += args =>
        {
            _pressureCheck.SelectId(args.Id);
            _dataPayload.PressureChecks = (VentPressureBound) args.Id;
            PumpDataChanged?.Invoke(_address, _dataPayload);
        };

        _copySettings.OnPressed += _ =>
        {
            PumpDataCopied?.Invoke(_dataPayload);
        };
    }

    public void ChangeData(GasVentPumpDataPayload dataPayload)
    {
        _dataPayload.Enabled = dataPayload.Enabled;
        _enabled.Pressed = _dataPayload.Enabled;

        _dataPayload.PumpDirection = dataPayload.PumpDirection;
        _pumpDirection.SelectId((int) _dataPayload.PumpDirection);

        _dataPayload.PressureChecks = dataPayload.PressureChecks;
        _pressureCheck.SelectId((int) _dataPayload.PressureChecks);

        _dataPayload.ExternalPressureBound = dataPayload.ExternalPressureBound;
        _externalBound.Value = _dataPayload.ExternalPressureBound;

        _dataPayload.InternalPressureBound = dataPayload.InternalPressureBound;
        _internalBound.Value = _dataPayload.InternalPressureBound;
    }
}